//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComToolOld.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComToolOld.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string btnCloseText {
            get {
                return ResourceManager.GetString("btnCloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启 的本地化字符串。
        /// </summary>
        internal static string btnOpenText {
            get {
                return ResourceManager.GetString("btnOpenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口通讯,网络通讯,USB通讯 的本地化字符串。
        /// </summary>
        internal static string ClientMode {
            get {
                return ResourceManager.GetString("ClientMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择要删除的文件. 的本地化字符串。
        /// </summary>
        internal static string ErrorDeleteFile {
            get {
                return ResourceManager.GetString("ErrorDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件已不存在. 的本地化字符串。
        /// </summary>
        internal static string ErrorDeleteFileExist {
            get {
                return ResourceManager.GetString("ErrorDeleteFileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请打开连接再发送. 的本地化字符串。
        /// </summary>
        internal static string ErrorNoClient {
            get {
                return ResourceManager.GetString("ErrorNoClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件格式出错. 的本地化字符串。
        /// </summary>
        internal static string ErrorReadFile {
            get {
                return ResourceManager.GetString("ErrorReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要写入的文件内容不能为空. 的本地化字符串。
        /// </summary>
        internal static string ErrorSaveDataText {
            get {
                return ResourceManager.GetString("ErrorSaveDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存文件名不能为空. 的本地化字符串。
        /// </summary>
        internal static string ErrorSaveFile {
            get {
                return ResourceManager.GetString("ErrorSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开连接失败! 的本地化字符串。
        /// </summary>
        internal static string ErrorStartClient {
            get {
                return ResourceManager.GetString("ErrorStartClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未检测到设备连接，请检查VID\PID以及设备连接状态！ 的本地化字符串。
        /// </summary>
        internal static string ErrorUSBStartClient {
            get {
                return ResourceManager.GetString("ErrorUSBStartClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏 的本地化字符串。
        /// </summary>
        internal static string ExpandClose {
            get {
                return ResourceManager.GetString("ExpandClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扩展 的本地化字符串。
        /// </summary>
        internal static string ExpandOpen {
            get {
                return ResourceManager.GetString("ExpandOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实现功能:  
        ///
        ///1.可根据需要选取串口通讯,网络通讯和USB通讯三种通讯方式.
        ///2.接收串口，网络和USB线传来的数据并进行显示.
        ///3.所接收到的数据显示方式可以选择字符方式或者HEX方式.
        ///4.中文显示无乱码,且不影响速度.
        ///5.串口通讯可以选择各个参数,并且串口设置和字符串操作等设置在程序关闭时会自动保存,打开时自动载入.网络通讯可以写入IP和端口,如果格式错误连接会出错.USB通讯可以搜索到Location，如果重复连接同一台机器会出错.
        ///6.可以发送HEX命令,但需要写好发送格式并勾选HEX发送.
        ///7.可以定时重复发送数据,并可以设置发送时间间隔.
        ///8.可以在发送字符串时选择发送新行,即自动加上回车换行.
        ///9.可以将接收文本框中的内容存储起来,也可以打开一个TEXT文档将内容读取到接收文本框.
        ///10.可以即时显示发送的字节数和接收的字节数,按清除按钮会清空文本框.
        ///11.扩展功能,多条命令字符串定义,每条字符串定义为字符串方式,可以以HEX发送.
        ///12.点击字符串右边的编号即可发送这条字符串.
        ///13.可以设置为循环发送你定义过的字符串,并且可以设置发送时间间隔.
        ///14. [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HelpInfomation {
            get {
                return ResourceManager.GetString("HelpInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无间隔,空格,换行,Tab格 的本地化字符串。
        /// </summary>
        internal static string ReceivedInterval {
            get {
                return ResourceManager.GetString("ReceivedInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无,总毫秒,时分秒 的本地化字符串。
        /// </summary>
        internal static string ShowTime {
            get {
                return ResourceManager.GetString("ShowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UDP通讯,TCP通讯 的本地化字符串。
        /// </summary>
        internal static string SocketClientMode {
            get {
                return ResourceManager.GetString("SocketClientMode", resourceCulture);
            }
        }
    }
}
